
Fmriprep on ADS5226

Container: /projects/adapt_lab/shared/containers/poldracklab_fmriprep_latest-2017-12-07-ba92e815fc4e.img

Subject directory: /projects/adapt_lab/shared/ADS/data/BIDS_data

Starting on: rest


181218-05:18:20,34 workflow IMPORTANT:
	 
    Running fMRIPREP version 1.0.0:
      * BIDS dataset path: /projects/adapt_lab/shared/ADS/data/BIDS_data.
      * Participant list: ['ADS5226'].
      * Run identifier: 20181218-051819_49d5c9d0-95a4-4dcf-a33d-54a6da3525dc.
    
181218-05:18:24,17 workflow IMPORTANT:
	 Creating bold processing workflow for "/projects/adapt_lab/shared/ADS/data/BIDS_data/sub-ADS5226/ses-wave2/func/sub-ADS5226_ses-wave2_task-rest_bold.nii.gz" (0.05 GB / 510 TRs).
181218-05:18:24,507 workflow IMPORTANT:
	 Slice-timing correction will be included.
181218-05:18:25,140 workflow WARNING:
	 No fieldmaps found or they were ignored, building base workflow for dataset /projects/adapt_lab/shared/ADS/data/BIDS_data/sub-ADS5226/ses-wave2/func/sub-ADS5226_ses-wave2_task-rest_bold.nii.gz.
181218-05:18:25,350 workflow IMPORTANT:
	 Creating BOLD surface-sampling workflow.
181218-05:18:26,424 workflow IMPORTANT:
	 Creating bold processing workflow for "/projects/adapt_lab/shared/ADS/data/BIDS_data/sub-ADS5226/ses-wave3/func/sub-ADS5226_ses-wave3_task-rest_bold.nii.gz" (0.05 GB / 510 TRs).
181218-05:18:26,829 workflow IMPORTANT:
	 Slice-timing correction will be included.
181218-05:18:27,383 workflow WARNING:
	 No fieldmaps found or they were ignored, building base workflow for dataset /projects/adapt_lab/shared/ADS/data/BIDS_data/sub-ADS5226/ses-wave3/func/sub-ADS5226_ses-wave3_task-rest_bold.nii.gz.
181218-05:18:27,574 workflow IMPORTANT:
	 Creating BOLD surface-sampling workflow.
181218-05:19:07,192 workflow WARNING:
	 [Node] Exception "fmriprep_wf.fsdir" (/projects/adapt_lab/shared/ADS/data/BIDS_data/derivatives/working_bids_fmripreprest/fmriprep_wf/fsdir)
181218-05:19:07,197 workflow ERROR:
	 Node fsdir failed to run on host n087.
181218-05:19:07,200 workflow ERROR:
	 Saving crash info to /projects/adapt_lab/shared/ADS/data/BIDS_data/derivatives/fmriprep/logs/crash-20181218-051907-pettitta-fsdir-b0b9c60c-38d6-48d4-9a90-3989da09d7a2.txt
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 404, in run
    self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 508, in _run_interface
    return self._run_command(execute)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 639, in _run_command
    result = self._interface.run()
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/interfaces/base/core.py", line 485, in run
    runtime = self._run_interface(runtime)
  File "/usr/local/miniconda/lib/python3.6/site-packages/fmriprep/interfaces/bids.py", line 357, in _run_interface
    copytree(source, dest)
  File "/usr/local/miniconda/lib/python3.6/shutil.py", line 309, in copytree
    os.makedirs(dst)
  File "/usr/local/miniconda/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/projects/adapt_lab/shared/ADS/data/BIDS_data/derivatives/freesurfer/fsaverage'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/plugins/multiproc.py", line 310, in _send_procs_to_workers
    self.procs[jobid].run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 408, in run
    os.remove(hashfile_unfinished)
FileNotFoundError: [Errno 2] No such file or directory: '/projects/adapt_lab/shared/ADS/data/BIDS_data/derivatives/working_bids_fmripreprest/fmriprep_wf/fsdir/_0xf09d7e3f27006003fd0dcc47b7f4e376_unfinished.json'

181218-05:19:09,148 workflow ERROR:
	 Node ds_validation_report failed to run on host n087.
181218-05:19:09,153 workflow ERROR:
	 Saving crash info to /projects/adapt_lab/shared/ADS/data/BIDS_data/derivatives/fmriprep/sub-ADS5226/log/20181218-051819_49d5c9d0-95a4-4dcf-a33d-54a6da3525dc/crash-20181218-051909-pettitta-ds_validation_report-3aa2ae7e-445f-4e58-980b-b07dc0dc29a0.txt
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/shutil.py", line 538, in move
    os.rename(src, real_dst)
FileNotFoundError: [Errno 2] No such file or directory: '/projects/adapt_lab/shared/ADS/data/BIDS_data/derivatives/working_bids_fmripreprest/fmriprep_wf/single_subject_ADS5226_wf/func_preproc_ses_wave2_task_rest_wf/func_reports_wf/ds_validation_report/_0xcd1c89c32e8559edb13d88583d3fa575_unfinished.json' -> '/projects/adapt_lab/shared/ADS/data/BIDS_data/derivatives/working_bids_fmripreprest/fmriprep_wf/single_subject_ADS5226_wf/func_preproc_ses_wave2_task_rest_wf/func_reports_wf/ds_validation_report/_0xcd1c89c32e8559edb13d88583d3fa575.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/plugins/multiproc.py", line 310, in _send_procs_to_workers
    self.procs[jobid].run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.6/site-packages/niworkflows/nipype/pipeline/engine/nodes.py", line 413, in run
    shutil.move(hashfile_unfinished, hashfile)
  File "/usr/local/miniconda/lib/python3.6/shutil.py", line 552, in move
    copy_function(src, real_dst)
  File "/usr/local/miniconda/lib/python3.6/shutil.py", line 251, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/local/miniconda/lib/python3.6/shutil.py", line 114, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/projects/adapt_lab/shared/ADS/data/BIDS_data/derivatives/working_bids_fmripreprest/fmriprep_wf/single_subject_ADS5226_wf/func_preproc_ses_wave2_task_rest_wf/func_reports_wf/ds_validation_report/_0xcd1c89c32e8559edb13d88583d3fa575_unfinished.json'




done

-------------------------------
